apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pv-kind
  namespace: 04--persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: manual-kind
  storageClassName: standard
