apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pv-kind
  namespace: 04--persistentvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
