apiVersion: v1
kind: Pod
metadata:
  name: manual-pv-and-pvc
  namespace: 04--persistentvolume
spec:
  containers:
    - name: nginx
      image: nginx:1.27.5-alpine
      volumeMounts:
        - name: storage
          mountPath: /some/mount/path
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: manual-pv-kind
