---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /home/mirza/Projects/kubernetes/03-installation-and-setup/kind-bind-mount-1
        containerPath: /some/path/in/container
  - role: worker
    extraMounts:
      - hostPath: /home/mirza/Projects/kubernetes/03-installation-and-setup/kind-bind-mount-2
        containerPath: /some/path/in/container
